### ISSUE TITLE
website çökmüş https://turkiyedepremapi.herokuapp.com/api

### ISSUE THREAD

**Issue by canbax** [emretanerc/sondepremlerApp#1]

**Comment by emretanerc** [comment]
Heroku ücretsiz paketlerini kaldırdı, bu sebeple backend servisi maalesef çalışmıyor.

**Comment by canbax** [comment]
biliyorum. Vercel ya da Netlify a geçebilirsiniz. Ya da statik site ise github-pages ı da kullanabilirsiniz

**Comment by emretanerc** [comment]
Backend API'sini ben yazmadım, maalesef. Bu arkadaş ile iletişime geçebilirsin.

https://github.com/berkekurnaz/Turkiye-Deprem-Api
